name: 'Package version selector'
description: '...'
inputs:
  owner:
    description: "Repository owner or organization"
    required: true
  repository:
    description: "Repository name"
    required: true
  package:
    description: "Package name"
    required: true
  filter:
    description: 'Filter string to get versions by name (optional)'
    required: false
  keep:
    description: "Number of versions to keep (default: 5)(optional)"
    reqired: false
    default: 5
  github-token:
    description: "Github token (use secrets.GITHUB_TOKEN)"
    required: true
outputs:
  versionids:
    description: 'Array of selected version ids'
runs:
  using: 'node12'
  main: 'select.js'
