name: CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: bdruesedow-imp/package-version-selector@master
      id: version-selector
      with:
        owner: ${{ github.actor }}
        repository: ${{ github.repository }}
        github-token: ${{ secrets.github_token }}
        package: "package-version-selector"
        keep: 1
        filter: "SNAPSHOT-"

    - run: echo ::set-env name=APPENDIX::${{ steps.version-selector.outputs.versionids }}
    - run: echo ${{ env.APPENDIX }}
